// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTodo = "todos"

// Todo mapped from table <todos>
type Todo struct {
	ID        string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Title     string         `gorm:"column:title;type:character varying(100);not null" json:"title"`
	Status    string         `gorm:"column:status;type:character varying(20);not null;default:pending" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp without time zone" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
