// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	FullName  string         `gorm:"column:full_name;type:character varying(45);not null" json:"full_name"`
	Phone     string         `gorm:"column:phone;type:character varying(15);not null" json:"phone"`
	Gender    string         `gorm:"column:gender;type:character varying(15);not null" json:"gender"`
	Email     string         `gorm:"column:email;type:character varying(100);not null" json:"email"`
	Password  string         `gorm:"column:password;type:character varying(100);not null" json:"password"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp without time zone" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
